theme: jekyll-theme-minimal
title: 游눹九뉦잺游늯游
description: Luismi CV
LUIS MIGUEL AND칔JAR BAENA
CURRICULUM
Mi experiencia
Soy una persona creativa con una gran trayectoria profesional en todos los aspectos de la formaci칩n, impartiendo tanto a empresas de diferente 칤ndole, (privadas o p칰blicas) y tama침o (multinacionales o pymes).
Aptitudes profesionales
Software: Diferentes suites de office tanto de pago (Microsoft Office) como de libre distribuci칩n (Open Office o Libre Office) y online (Suite de Google, Suite de Microsoft)  Dise침o: Diferente software de retoque fotogr치fico.
Contacta conmigo:
Correo electr칩nico: correo.andujar@gmail.com
Experiencia laboral
- M치s o menos el mismo trabajo que en el apartado superior.
- En alguno de los centros tambi칠n realizamos montaje y configuraci칩n de equipos inform치ticos.
- En alg칰n centro realic칠 tareas de b칰squeda de subvenciones y cursos en diferentes administraciones.
Profesor
Diferentes centros de estudios | 1997 - 2019
Educaci칩n previa

ALMI Centro acad칠mico Bilbao
T칠cnico Auxiliar Administrativo, 1986
- Curso sobre t칠cnicas, psicolog칤a y actividades para impartir clases.
- Resoluci칩n de problemas tanto individuales como en grupo.
- Preparaci칩n de pruebas, dirigidas a el control de conocimientos en las diferentes materias impartidas.
METODOLOG칈A DID츼CTICA (Formaci칩n de formadores)
Formaci칩n de formadores, 2009
Otras formaciones
- En este curr칤culum reflejo solo una parte de la vida laboral. 
- Para cualquier consulta o aclaraci칩n sobre el curr칤culum  pueden ponerse en contacto en el e-mail: correo.andujar@gmail.com
Administraci칩n de Sistemas de Red en Linux.
Virtualizaci칩n de Sistemas Workstation y Server
DATA SCIENCE Bootcamps THE BRIDGE 2023
- Analizar grandes vol칰menes de datos.
 - Programaci칩n en Python y manejo de diferentes librer칤as . 
 - Matem치ticas para resolver problemas complejos y obtener as칤 informaci칩n de valor para la toma de decisiones.
 - Utilizaci칩n de diferentes algoritmos para el an치lisis de datos.
redes sociales:
www.youtube.com/@accesibilidadconluismi
YouTube:
- Guiar al los equipos de alumnos y conducirlos para conocer una nueva herramienta o ampliar conocimientos de una que ya utilizan.
- Mantener un ambiente jovial y de equipo.
Profesor
Talio antes Ibex servicios inform치ticos | 2010-presente
Bridge Education Bilbao | Presente
- Teacher Assistant Bootcamp Data Science, en colaboraci칩n con la Fundaci칩n BBK y 
Lanbide (SEPE en el Pa칤s Vasco).
www.linkedin.com/in/luismi-andujar
Linkedin
